iam: remove invalid Bucket param from list_buckets()
> botocore.exceptions.ParamValidationError: Parameter validation failed:
> Unknown parameter in input: "Bucket", must be one of: MaxBuckets, ContinuationToken, Prefix, BucketRegion

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 41b7297e7af6c1c794c075249732ebd6d8845f98)